version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: farmtimems-postgres-dev
    environment:
      POSTGRES_DB: farmtimems
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/Database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d farmtimems"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: farmtimems-postgres-test
    environment:
      POSTGRES_DB: farmtimems_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - testing

volumes:
  postgres_dev_data:
    driver: local
  postgres_test_data:
    driver: local

networks:
  default:
    name: farmtimems-network
