// <auto-generated />
using System;
using COMP9034.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace COMP9034.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250917155704_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("COMP9034.Backend.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PerformedByStaffId")
                        .HasColumnType("integer");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByStaffId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.BiometricData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BiometricType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeviceEnrollment")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateHash");

                    b.HasIndex("StaffId", "BiometricType")
                        .IsUnique();

                    b.ToTable("BiometricData");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.BiometricVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerificationId"));

                    b.Property<int?>("BiometricId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,3)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("VerificationId");

                    b.HasIndex("BiometricId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventId");

                    b.HasIndex("StaffId");

                    b.HasIndex("VerificationResult");

                    b.ToTable("BiometricVerification", (string)null);
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Device", (string)null);

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            CreatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(8040),
                            DeviceName = "Main Terminal",
                            DeviceType = "terminal",
                            IpAddress = "192.168.1.100",
                            IsActive = true,
                            Location = "Main Entrance",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(8040)
                        },
                        new
                        {
                            DeviceId = 2,
                            CreatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(8040),
                            DeviceName = "Biometric Scanner",
                            DeviceType = "biometric",
                            IpAddress = "192.168.1.101",
                            IsActive = true,
                            Location = "Security Office",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(8040)
                        });
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StaffId")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("AdminId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("StaffId", "OccurredAt");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_type", "\"EventType\" IN ('CLOCK_IN','CLOCK_OUT','BREAK_START','BREAK_END','MANUAL_OVERRIDE')");
                        });
                });

            modelBuilder.Entity("COMP9034.Backend.Models.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Username", "Timestamp");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<decimal>("GrossPay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OvertimeHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OvertimePay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PayPeriodEnd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayPeriodStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RegularPay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TotalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.HasKey("SalaryId");

                    b.HasIndex("Status");

                    b.HasIndex("StaffId", "PayPeriodStart", "PayPeriodEnd");

                    b.ToTable("Salary", (string)null);
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Casual");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OvertimePayRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StandardHoursPerWeek")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(40);

                    b.Property<decimal>("StandardPayRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StaffId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Staff", (string)null);

                    b.HasData(
                        new
                        {
                            StaffId = 9001,
                            ContractType = "FullTime",
                            CreatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 656, DateTimeKind.Utc).AddTicks(3880),
                            Email = "admin@farmtimems.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            OvertimePayRate = 75.00m,
                            PasswordHash = "$2a$11$nztUxg5SMp5Be9UnjOipBeUmeYIxMUleUVf.J/GE38ioHXA8j1AF6",
                            Pin = "1234",
                            Role = "Admin",
                            StandardHoursPerWeek = 40,
                            StandardPayRate = 50.00m,
                            UpdatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 656, DateTimeKind.Utc).AddTicks(3880),
                            Username = "admin"
                        },
                        new
                        {
                            StaffId = 8001,
                            ContractType = "FullTime",
                            CreatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 790, DateTimeKind.Utc).AddTicks(5710),
                            Email = "manager@farmtimems.com",
                            FirstName = "Farm",
                            IsActive = true,
                            LastName = "Manager",
                            OvertimePayRate = 52.50m,
                            PasswordHash = "$2a$11$Qti/DzU6MhFc6Cz4dDGl4.D5xWkHQY5RG7E2EKMatI3tmOB4cSjae",
                            Pin = "8001",
                            Role = "Manager",
                            StandardHoursPerWeek = 40,
                            StandardPayRate = 35.00m,
                            UpdatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 790, DateTimeKind.Utc).AddTicks(5710),
                            Username = "manager"
                        },
                        new
                        {
                            StaffId = 1001,
                            ContractType = "Casual",
                            CreatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(7690),
                            Email = "worker@farmtimems.com",
                            FirstName = "Farm",
                            IsActive = true,
                            LastName = "Worker",
                            OvertimePayRate = 37.50m,
                            PasswordHash = "$2a$11$qB30P0mxt3bESfOwYrBCv.XumZ8UjsiXfkQupgMrl9WrvHfANhPWe",
                            Pin = "1001",
                            Role = "Staff",
                            StandardHoursPerWeek = 20,
                            StandardPayRate = 25.00m,
                            UpdatedAt = new DateTime(2025, 9, 17, 15, 57, 3, 924, DateTimeKind.Utc).AddTicks(7690),
                            Username = "worker"
                        });
                });

            modelBuilder.Entity("COMP9034.Backend.Models.WorkSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ScheduleHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ScheduledDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.HasIndex("StaffId", "ScheduledDate");

                    b.ToTable("WorkSchedule", (string)null);
                });

            modelBuilder.Entity("COMP9034.Backend.Models.AuditLog", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "PerformedByStaff")
                        .WithMany()
                        .HasForeignKey("PerformedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByStaff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.BiometricData", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany("BiometricData")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.BiometricVerification", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.BiometricData", "Biometric")
                        .WithMany()
                        .HasForeignKey("BiometricId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COMP9034.Backend.Models.Device", "Device")
                        .WithMany("BiometricVerifications")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COMP9034.Backend.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany("BiometricVerifications")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Biometric");

                    b.Navigation("Device");

                    b.Navigation("Event");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Event", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COMP9034.Backend.Models.Device", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany("Events")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("Device");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.LoginLog", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Salary", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany("Salaries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.WorkSchedule", b =>
                {
                    b.HasOne("COMP9034.Backend.Models.Staff", "Staff")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Device", b =>
                {
                    b.Navigation("BiometricVerifications");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("COMP9034.Backend.Models.Staff", b =>
                {
                    b.Navigation("BiometricData");

                    b.Navigation("BiometricVerifications");

                    b.Navigation("Events");

                    b.Navigation("Salaries");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
